services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SQL_NAME}
      POSTGRES_USER: ${SQL_USERNAME}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: anansi_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      SQL_ENGINE: ${SQL_ENGINE}
      SQL_NAME: ${SQL_NAME}
      SQL_USERNAME: ${SQL_USERNAME}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
    ports:
      - "8000:8000"
volumes:
  postgres_data: