version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes:
      - staticfiles:/anansi_app/static
      - mediafiles:/anansi_app/media
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: ./compose/production/web/Dockerfile
    image: anansi_project_prod_web
    command: /start
    volumes:
      - staticfiles:/anansi_app/static
      - mediafiles:/anansi_app/media
    env_file:
      - ./.env/.prod-sample
    environment:
        - RECAPTCHA_PRIVATE_KEY
        - RECAPTCHA_PUBLIC_KEY
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=anansi_project
      - POSTGRES_USER=anansi_project
      - POSTGRES_PASSWORD=anansi_project
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  staticfiles:
  mediafiles:
