#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /anansi_project/manage.py collectstatic --noinput
python /anansi_project/manage.py migrate

/usr/local/bin/gunicorn anansi_app.wsgi:application --bind 0.0.0.0:8000 --chdir=/anansi_app
