FROM node:16-stretch-slim as frontend-builder

WORKDIR /anansi_app
COPY . .

RUN npm install
RUN npm run build
RUN npm run start

FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update --yes --quiet && apt-get install --yes --quiet --no-install-recommends \
    build-essential \
    libpq-dev \
    libmariadbclient-dev \
    libjpeg62-turbo-dev \
    zlib1g-dev \ 
    libwebp-dev \ 
&& rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./compose/local/web/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY ./compose/local/web/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

WORKDIR /anansi_app

RUN mkdir /anansi_app/static
RUN mkdir /anansi_app/media

# copy project code
COPY . .
COPY --from=frontend-builder /anansi_app/frontend/build /anansi_app/frontend/build

RUN chown -R django:django /anansi_app

USER django

ENTRYPOINT ["/entrypoint"]